//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTech_MaverickDistributing
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManufacturerType
    {
        public ManufacturerType()
        {
            this.Manufacturers = new HashSet<Manufacturer>();
        }
    
        public string ManufacturerTypeName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int ManufacturerTypeID { get; set; }
    
        public virtual ICollection<Manufacturer> Manufacturers { get; set; }
    }
}
