//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTech_MaverickDistributing
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class md_dbEntities : DbContext
    {
        public md_dbEntities()
            : base("name=md_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<EquipmentType> EquipmentTypes { get; set; }
        public virtual DbSet<EquipmentYear> EquipmentYears { get; set; }
        public virtual DbSet<Make> Makes { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<ManufacturerType> ManufacturerTypes { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<PartsView> PartsViews { get; set; }
    
        public virtual ObjectResult<GetPartsInfo_Result> GetPartsInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPartsInfo_Result>("GetPartsInfo");
        }
    }
}
