//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTech_MaverickDistributing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public int MakeID { get; set; }
        public int TypeID { get; set; }
        public int CategoryID { get; set; }
        public int ModelID { get; set; }
        public int YearID { get; set; }
        public int ManufacturerID { get; set; }
        public string PartNumber { get; set; }
        public string PartDesc { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ImageFilePath { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int PartID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual EquipmentType EquipmentType { get; set; }
        public virtual Make Make { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Model Model { get; set; }
    }
}
